# Generated by Django 5.2.12 on 2026-04-08 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('current_price', models.FloatField()),
                ('direction', models.CharField(max_length=20)),
                ('confidence', models.FloatField()),
                ('insight', models.TextField()),
                ('risk_level', models.CharField(max_length=20)),
                ('nlp_score', models.FloatField(default=0.0)),
                ('max_drawdown', models.FloatField(default=0.0)),
                ('value_at_risk', models.FloatField(default=0.0)),
                ('risk_reward', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
