# Generated by Django 5.2.12 on 2026-04-19 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_marketcandle'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='marketcandle',
            new_name='market_mark_symbol_b09f50_idx',
            old_name='market_mark_symbol__c66d32_idx',
        ),
    ]
